apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/narendra311777/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
    #path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
  - syncOptions: 
    CreateNamespace: true
    automated:
      selfHeal: true // if any  changes apply from kubectl it will revert
      prune: true  //if any file deleted in config it deletes that conf in clust
